AppBundle\Entity\Products:
    type: entity
    table: products
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
        name:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
        description:
            type: string
            nullable: false
            length: 500
            options:
                fixed: false
        brand:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
        category:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
        price:
            type: decimal
            nullable: false
            precision: 9
            scale: 0
    lifecycleCallbacks: {  }
